version: '3'
services:
  quants_forecast: 
    build:
      context: .
      dockerfile: Dockerfile
    image: quants_forecast
    ports:
    - "8888:8888"
    volumes:
    - ../quats_data_dir:/data_dir
    - ./Chapter02/archive:/opt/ml
    - ./notebook/:/notebook
    environment:
      PYTHONPATH: /opt/ml/src
    tty: true